version: '3.8'
services:
  sd2example:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    volumes:
      - .:/app  # ✅ Ensure the entire project is mapped inside
    working_dir: /app
    ports:
      - "3000:3000"
    command: ["node", "index.js"]

  web:
    build:
      context: .
    volumes:
      - .:/app  # ✅ Ensure the entire project is mapped inside
    working_dir: /app
    ports:
      - "3001:3001"
    command: ["node", "index.js"]
    depends_on:
      - db

  db:
    image: mysql
    restart: always
    env_file:
      - ./.env
    ports:
      - "3308:3306"
    volumes:
      - db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    platform: linux/amd64
    env_file:
      - ./.env
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  db-data:
